# Generated by Django 4.2.13 on 2024-06-28 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
