# Generated by Django 4.2.13 on 2024-06-30 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_remove_user_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('password', models.CharField(max_length=255, null=True)),
                ('date_received', models.DateTimeField(null=True)),
                ('date_allow_receipt', models.DateField(null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_rel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.profile')),
            ],
        ),
    ]
