# Generated by Django 4.2.13 on 2024-06-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('SU', 'Suspend'), ('RE', 'Received')], default='SU', max_length=3),
        ),
    ]
