# Generated by Django 4.2.13 on 2024-06-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('cvv2', models.CharField(max_length=4)),
                ('expiration_date', models.DateField()),
                ('stock', models.PositiveBigIntegerField(default=0)),
                ('profile_rel', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='account.profile')),
            ],
        ),
    ]
